# topology
nodes: [host1, router, host2]
links: [[link1, host1, router],[link2, router, host2]]

# pcap generation config
interface_link: link2
interface_link_side: host2
duration_type: number_packets
duration: 100

# user-specified packets
my_packet_1:
  layers: [eth, ipv6, icmpv6]
  eth:
    src_mac:
      distribution_type: static
      values: [00:00:00:00:00:03]
    dst_mac:
      distribution_type: static
      values: [00:00:00:00:00:02]
    eth_type:
      distribution_type: static
      values: [0x86dd]
  ipv6:
    version:
      distribution_type: static
      values: [6]
    traffic_class:
      distribution_type: static
      values: [0]
    differentiated_services:
      distribution_type: static
      values: [0]
    ecn:
      distribution_type: static
      values: [0]
    flow_label:
      distribution_type: static
      values: [0]
    payload_length:
      distribution_type: static
      values: [0]
    next_header:
      distribution_type: static
      values: [58]
    hop_limit:
      distribution_type: static
      values: [128]
    ip_src:
      distribution_type: static
      values: [0000:0000:0000:0000:0000:0000:0000:0001]
    ip_dst:
      distribution_type: static
      values: [0000:0000:0000:0000:0000:0000:0000:0002]
  icmpv6:
    type:
      distribution_type: static
      values: [128]
    code:
      distribution_type: static
      values: [0]

# configuration of nodes
host1:
  ip_address: 10.0.0.2
  mac_address: 00:00:00:00:00:02
  application_layer_roles: [arp_client, arp_server]
  role_specific_delay_distribution_types: [static, static]
  role_specific_delay_distribution_values: [[2], [3]]
  user_specified_traffic: 
    link1: 
      pcap_file_specified: false
      pcap_file_path: pcaps/arp.pcap
      messages: []
      delay_distribution_types: []
      delay_distribution_options: [[]]
      delay_distribution_values: [[]]
  serialization_delay: 1

host2:
  ip_address: 10.0.0.3
  mac_address: 00:00:00:00:00:03
  application_layer_roles: []
  role_specific_delay_distribution_types: []
  role_specific_delay_distribution_values: []
  user_specified_traffic:
    link2: 
      pcap_file_specified: false
      pcap_file_path: pcaps/out.pcap
      messages: [my_packet_1]
      delay_distribution_types: [index_uniform]
      delay_distribution_options: [[]]
      delay_distribution_values: [[200, 300]]
  serialization_delay: 1

router: 
  ip_address: 10.0.0.1
  mac_address: 00:00:00:00:00:01
  application_layer_roles: []
  role_specific_delay_distribution_types: []
  role_specific_delay_distribution_values: [[]]
  user_specified_traffic: []
  serialization_delay: 1

# configuration of links
link1:
  delay_distribution_type: static
  delay_values: [15000000]
  packet_loss_distribution_type: none
  packet_loss_values: []
  packet_corruption_distribution_type: none
  packet_corruption_values: []

link2:
  delay_distribution_type: static
  delay_values: [300]
  packet_loss_distribution_type: none
  packet_loss_values: []
  packet_corruption_distribution_type: none
  packet_corruption_values: []
